gui:
  theme:
    selectedLineBgColor:
      - cyan

git:
  log:
    showGraph: always

  branchLogCmd: 'git log --color=always --decorate --oneline --graph {{branchName}}'
  allBranchesLogCmd: 'git log --color=always --decorate --oneline --graph --all'
