gui:
  theme:
    selectedLineBgColor:
      - reverse

git:
  log:
    showGraph: always

  paging:
    colorArg: always
    pager: delta --light --paging=never

  branchLogCmd: 'git log --color=always --decorate --oneline --graph {{branchName}}'
  allBranchesLogCmd: 'git log --color=always --decorate --oneline --graph --all'

os:
  editPreset: 'vscode'

promptToReturnFromSubprocess: false

customCommands:
  # Ctrl-g (think "go") to run 'just' within repo
  - key: '<c-g>'
    context: 'global'
    command: "just"
    subprocess: true
    description: "Run 'just' (default target)"
    stream: true

  # Ctrl-slash (think "diagonal space") to show selected commit
  - key: '<c-/>'
    context: 'commits'
    command: "git show {{.SelectedLocalCommit.Sha}} ; read -sr -n 1 -p 'Press any key...'"
    subprocess: true
    description: "Show selected commit"
