gui:
  theme:
    selectedLineBgColor:
      - reverse

git:
  log:
    showGraph: always

  paging:
    colorArg: always
    pager: delta --light --paging=never

  branchLogCmd: 'git log --color=always --decorate --oneline --graph {{branchName}}'
  allBranchesLogCmd: 'git log --color=always --decorate --oneline --graph --all'
