#!/usr/bin/env python3

"""Open common applications by group."""

# pylint: disable=missing-function-docstring

import argparse
import os
import subprocess
import sys
import time

EMACS_OPEN_SCRIPT = "~/sw/emacsopen/emacsopen"

IS_WEKA = os.path.exists(os.path.expanduser("~/.mh-flag-weka"))
IS_PERSONAL = not IS_WEKA

CALENDAR_APP = "Fantastical"
BROWSER_APP = "Google Chrome" if IS_WEKA else "Safari"


def open_apps(apps):
    """Open each application in the given list with a slight delay."""
    for app in apps:
        try:
            subprocess.run(["open", "-a", app], check=True)
            time.sleep(0.2)
        except subprocess.CalledProcessError:
            ...  # Note: 'open -a' already prints an error if app not found


def open_emacs():
    emacsopen = os.path.expanduser(EMACS_OPEN_SCRIPT)
    if os.path.exists(emacsopen):
        subprocess.run(
            [emacsopen],
            check=True,
        )
    else:
        print(f"Emacs open script not found: {emacsopen}")


def open_todos():
    apps = [
        "Things3",
        BROWSER_APP,
        CALENDAR_APP,
    ]
    if IS_PERSONAL:
        apps.append("Claude")
        apps.append("WorkFlowy")

    open_apps(apps)
    open_url("obsidian://open?vault=code-vault")

    if IS_PERSONAL:
        open_url("obsidian://open?vault=private-vault")
    if IS_WEKA:
        open_url("https://linear.app/kamihq/my-issues")
        open_url("https://www.notion.so/kamiapp/EMPTY-17aa3ed0d3f1809c8b79d3dd78fad0a5")
        open_url("obsidian://open?vault=kork-vault")


def open_dev():
    dev_apps = [
        "iTerm",
        "Visual Studio Code",
    ]
    if IS_PERSONAL:
        dev_apps += [
            "Claude",
        ]
    if IS_WEKA:
        dev_apps += [
            "Cursor",
            "Docker Desktop",
            "RubyMine",
        ]

    open_apps(dev_apps)
    if IS_WEKA:
        for url in [
            "https://github.com/pulls/inbox",
            "https://github.com/pulls/involves?q=involves%3A%40me+state%3Aopen+sort%3Aupdated-desc+org%3AKamiHQ",
        ]:
            open_url(url)
    if IS_PERSONAL:
        for url in [
            "https://github.com/pulls/involves?q=involves%3A%40me+state%3Aopen+sort%3Aupdated-desc+-org%3AKamiHQ",
        ]:
            open_url(url)


def open_comms():
    comms_apps = ["Mimestream", BROWSER_APP]
    if IS_PERSONAL:
        comms_apps += [
            "Messages",
            "Messenger",
            "WhatsApp",
        ]
        open_url("https://www.facebook.com/notifications")
    if IS_WEKA:
        comms_apps += [
            "Slack",
        ]

    open_apps(comms_apps)


def open_music():
    music_apps = []
    if IS_PERSONAL:
        music_apps += [
            "Dorico 6",
            "forScore",
            "GarageBand",
            "iReal Pro",
            "Music",
            "RealPlay",
            "VoiceMemos",
        ]

    open_apps(music_apps)


def open_all():
    open_todos()
    open_dev()
    open_comms()
    # open_emacs()
    open_music()


def open_url(url: str):
    """Open a URL in the default browser."""
    subprocess.run(["open", url], check=True)


def main():
    parser = argparse.ArgumentParser(description="Open groups of apps.")
    choices = ["todos", "dev", "comms", "music", "all"]
    default = "all"
    assert default in choices
    parser.add_argument(
        "group",
        nargs="?",  # TODO:revisit this
        default=default,
        choices=choices,
        help=f"Which app group to open: {', '.join(choices)} (default={default})",
    )
    args = parser.parse_args()

    if args.group == "todos":
        open_todos()
    elif args.group == "dev":
        open_dev()
    elif args.group == "comms":
        open_comms()
    elif args.group == "music":
        open_music()
    elif args.group == "all":
        open_all()
    else:
        print(f"Unknown group: {args.group}. Available options: {', '.join(choices)}")
        sys.exit(1)


if __name__ == "__main__":
    if sys.platform != "darwin":
        print("This script is intended for macOS only.")
        sys.exit(1)
    main()
