#!/usr/bin/env zsh
# shellcheck shell=bash

# Tests the chezmoi source configration against the local state,
# displays differences if any, and applies changes on user confirmation.

if chezmoi verify; then
  echo "Already in sync, nothing to do"
  exit 0
fi

mh-horizontal-line -n 2
chezmoi diff
mh-horizontal-line
chezmoi status
mh-horizontal-line
echo 'Proceed? y/N'

read -sqr answer

if [[ "$answer" == "y" ]]; then
  mh-chezmoi-helper apply
else
  echo "Cancelled by user"
  exit 1
fi
