#!/usr/bin/env python3

import asyncio
import os
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

MAX_PARALLEL_JOBS = 16
DEBUG = False
H_LINE = "_" * 30

# Interactive (not for parsing) script to run the given shell command
# in parallel across all found git or JJ repositories in the home directory
# found by fd.
#
# Intended for interactive use, not for parsing.
#
# Top level commands:
# - `p <shell-command>`: Run the command in parallel across all repositories.
# - `s <shell-command>`: Run the command sequentially across all repositories.
#
# The shell command can be expressed as a single string, and multiple arguments
# will just be concatenated with spaces to pass as a single shell command.
#
# Parallel mode will refuse to run if the command contains keywords that suggest
# a call to a TUI.
#
# Sequential mode is more verbose and allows for interactive commands.
# In the sequential mode, stdin, stdout, and stderr are all connected.
#
# In parallel mode, the command is run in the background, and stdout/stderr
# are printed only if the command fails or produces output.

# Finds all directories in the home directory that are Git or JJ repositories.
# Symlinks are not followed.
# Hint: Tune ~/.fdignore for speed

# External dependencies: fd, jj, git, bash, and (in this repo): j-pull

# TODO:automatically bind mr foo to mr p j foo, whenever j-foo exists
# TODO:QA pass including docs, and ruff checks
# TODO:clean up now dead code via czun on weka
# TODO:zsh completion
# TODO:add a 'here' alternative to parallel/sequential, to run at current repo top?
# TODO:add a quiet option to suppress decorations (and maybe suppress filters too)
# TODO:maybe try to handle spaces, or shell quoting etc, when needing to pass in args with spaces? bash vs cmd?
# TODO:consider more explicit etc mr (s|p) (list|pull|st-l|st-s|shun((bash|cmd) <shell-command> [args...]))
# TODO:support either a pager, or otherwise read one repo at a time: alt: use Bat
# TODO:with subcommands calling to other commands (like j-pull), add smart ways to check for various levels of dirty
# TODO:prevent nesting of repos (eg submodules)
# TODO:consider always checking for .git+.jj in each repo, failing fast if any missing
# TODO:add j-* commands for all the git ops I want to do
# TODO:Add -x filter (as very first arg) to filter out repos, e.g. `mr -x code-n,rustlings` todo. and reverse of -j for just
# TODO:all main commands should support `--color=always` to keep colors in output. look at injecting automatically, if main command. eg all lints
# TODO:failure in any of the steps should result in exiting with a useful error code. consider 1 for failure in a step, or 2 for failure in this script (or bad args etc)


HOME_DIR = Path.home()
EXCLUDED_REPOS = [f"{HOME_DIR}/.config/emacs"]


@dataclass(frozen=True)
class CommandResult:
    """Class to hold the result of a command execution."""

    repo_path: str
    stdout: str
    stderr: str
    returncode: int


def fail(msg) -> SystemExit:
    """Prints an error message to stderr and exits with code 1.
    Callers can 'raise fail(...)' rather than 'fail(...)' to work around type checking issues.
    """
    print(msg, file=sys.stderr)
    sys.exit(1)
    # noinspection PyUnreachableCode
    return SystemExit(1)


def debug(msg):
    """Prints a debug message to stderr if DEBUG is enabled."""
    if DEBUG:
        print(f"DEBUG: {msg}", file=sys.stderr)


forbidden_parallel_keywords = (
    "jjui",
    "lazygit",
    "tig",
)


def get_repos_or_fail() -> list[str]:
    """Returns list of jj/git repository paths."""
    try:
        repos_output = subprocess.check_output(
            [
                "fd",
                "--hidden",
                "--type",
                "directory",
                "--prune",
                r"^\.(git|jj)$",
                HOME_DIR,
            ],
            text=True,
        )
    except subprocess.CalledProcessError:
        raise fail("Failed to find repositories.")
    repo_paths = [
        r.removesuffix(os.sep)
        .removesuffix(".git")
        .removesuffix(".jj")
        .removesuffix(os.sep)
        for r in repos_output.splitlines()
        if r
    ]
    # Filter, remove duplicates (via set creation), and sort
    repo_paths = sorted({repo for repo in repo_paths if repo not in EXCLUDED_REPOS})
    if not repo_paths:
        fail("No repositories found to run command in.")

    return repo_paths


class colors:
    GREEN = "\033[32m"
    BLUE = "\033[34m"
    ENDC = "\033[0m"


def print_color(text: str, color: str):
    """Prints the given text in the specified color."""
    print(f"{color}{text}{colors.ENDC}")


def run_sequential(repo_paths: list[str], command_with_args: list[str]):
    """Runs a shell command in each repository sequentially."""
    for repo_path in repo_paths:
        debug(
            f"Running command in repository: {repo_path}, command: {command_with_args}"
        )
        print_color(f"{H_LINE}\n{repo_path}", colors.GREEN)
        process = subprocess.run(
            command_with_args,
            cwd=repo_path,
            text=True,
            check=False,
        )
        if is_returncode_failure(process.returncode, command_with_args[0]):
            print(f">> Command failed with exit code {process.returncode}")
        debug(f"Done running command in repository: {repo_path}")


COMMANDS_ALLOWING_RETURNCODE_1 = ("rg", "grep")


def is_returncode_failure(returncode: int, command: str) -> bool:
    """Determines if the return code indicates a failure for the given command."""
    if returncode == 0:
        return False
    if command in COMMANDS_ALLOWING_RETURNCODE_1 and returncode == 1:
        return False
    return True


def run_parallel(repo_paths: list[str], command_and_args: list[str]):
    combined_command = " ".join(command_and_args)
    used_forbidden_keywords = [
        keyword
        for keyword in forbidden_parallel_keywords
        if keyword in combined_command
    ]
    if used_forbidden_keywords:
        fail(
            "Command contains forbidden keywords for parallel execution:\n"
            ">> " + f"{', '.join(used_forbidden_keywords)}" + "\n"
            "Please run in sequential mode instead."
        )
        return

    async def run_repo(repo_path):
        async with run_repo.sem:
            debug(
                f"Running command in repository: {repo_path}, command: {command_and_args}"
            )
            process = await asyncio.create_subprocess_exec(
                *command_and_args,
                cwd=repo_path,
                stdin=None,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            stdout, stderr = await process.communicate()

            debug(f"Done running command in repository: {repo_path}")
            return CommandResult(
                repo_path=repo_path,
                stdout=stdout.decode(),
                stderr=stderr.decode(),
                returncode=process.returncode,
            )

    run_repo.sem = asyncio.Semaphore(MAX_PARALLEL_JOBS)

    async def parallel_main():
        return await asyncio.gather(*(run_repo(r) for r in repo_paths))

    process_results = asyncio.run(parallel_main())
    for result in process_results:
        is_failure = is_returncode_failure(result.returncode, command_and_args[0])
        if is_failure or result.stderr or result.stdout:
            print_color(f"{H_LINE}\n{result.repo_path}", colors.GREEN)
            if result.stdout:
                print(result.stdout)
            if result.stderr:
                print(">> Stderr output:")
                print("\n>> ".join(result.stderr.splitlines()))
            if is_failure:
                print(f">> Command failed with exit code {result.returncode}")


FLAG_PARALLEL = "p"
FLAG_SEQUENTIAL = "s"
FLAG_LIST = "list"

ALIASES = {
    "fd": [FLAG_PARALLEL, "fd"],
    "ju": [FLAG_SEQUENTIAL, "bash", "-c", "read -n 1 -s -p 'Press any key...' ; jjui"],
    "lint": [FLAG_PARALLEL, "j-lint"],
    "pull": [FLAG_PARALLEL, "j-pull", "--color=always"],
    "rg": [FLAG_PARALLEL, "rg", "--color=always"],
    "shun": [FLAG_PARALLEL, "j-shun"],
    "st-l": [FLAG_PARALLEL, "git", "status"],
    "st-s": [FLAG_PARALLEL, "git", "status", "--short"],
    "todo": [
        FLAG_PARALLEL,
        "rg",
        "--color=always",
        "--hidden",
        "--ignore-case",
        "todo|fixme|hack",
    ],
}


ALIAS_DESCRIPTIONS = "\n    ".join(
    [f"mr {alias} * => mr " + " ".join(ALIASES[alias]) + " *" for alias in ALIASES]
)
USAGE = f"""
Usage: mr (<ALIAS> [args...]|({FLAG_PARALLEL}|{FLAG_SEQUENTIAL}) <command> [args...])\n

Examples:
    mr {FLAG_PARALLEL} git status
    mr {FLAG_SEQUENTIAL} bash -c 'git status; read -p "Press enter to continue..."'

Aliases:
    {ALIAS_DESCRIPTIONS}
"""


def main(args: list[str]) -> int:
    """
    Main function to parse arguments and run the command in repositories.
    Args:
        args (list): Given command line arguments. Excludes script name.
    """
    if len(args) < 1:
        fail(f"Error: No subcommand provided.\n{USAGE}")

    mode = args[0]

    if mode == FLAG_LIST:
        repo_paths = get_repos_or_fail()
        for repo in repo_paths:
            print(repo)
        return 0

    if len(args) > 0 and mode in ALIASES:
        return main(ALIASES[mode] + args[1:])

    if mode not in (
        FLAG_PARALLEL,
        FLAG_SEQUENTIAL,
    ):
        fail(f"Unknown top level mode or alias: {mode}\n{USAGE}")

    if len(args) < 2:
        fail(f"Error: missing command to run.\n{USAGE}")

    repo_paths = get_repos_or_fail()
    debug(f"Found {len(repo_paths)} repositories to run command in.")

    command_and_args = args[1:]

    if mode == FLAG_PARALLEL:
        run_parallel(repo_paths, command_and_args)
    else:
        run_sequential(repo_paths, command_and_args)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
