#!/bin/bash

function fail {
  echo "$*" >&2
  exit 1
}

function hl {
  mh-horizontal-line
}

# TODO: Audit, make it more complete, and improve output. And test! And make it allow to have tools missing
hl
echo Docker:
docker ps -a |grep -Ev '^CONTAINER'

hl
echo Codespaces:
gh codespace list | cat

hl
echo UTM VMs:
# Only call AppleScript if UTM has any VMs on disk (to lessen the need to open the app), as seldom used
UTM_VM_DIR="$HOME/Library/Containers/com.utmapp.UTM/Data/Documents"
if [[ -d "$UTM_VM_DIR" && -n "$(find "$UTM_VM_DIR" -name '*.utm')" ]]; then
  /Applications/UTM.app/Contents/MacOS/utmctl list | grep -Ev 'UUID';
fi

hl
echo Tart VMs:
tart list | grep -E '^local'
hl
