#!/bin/zsh
# shellcheck shell=bash

# Syntax: single-run-zsh-interactive [-profile]
# -profile: Enable profiling of zsh startup using zprof

if [[ "$1" == "-profile" ]]; then
  export MH_PROFILE_ZSHRC=true
  shift 1
fi

# Check that no other arguments were passed
if [[ "$#" -ne 0 ]]; then
  echo "Unexpected arguments: $*"
  echo "Syntax: $0 [-profile]"
  exit 1
fi

# Perform single run of zsh in interactive mode,
# immediately calling exit to terminate the shell.
# Include 'true' otherwise the shell exits with return code 1.
zsh -i -c 'true; exit'
