#!/bin/bash
# shellcheck disable=SC1091  # Don't follow sources

# Installs core software, taking into account desired state

function fail {
  echo "$*" >&2
  exit 1
}

function assert_function {
  type -t "$1" >/dev/null 2>&1 || fail "Required function not found: $1"
}

function hl { mh-horizontal-line; }

source_dir="$(dirname "${BASH_SOURCE[0]}")"
impl_dir="${source_dir}/mh-install.d"

# Note: order is significant
# TODO: make these switchable chezmoi style by moving these to a non-sorted desired list
# TODO: generally make zsh config allow any of the tools here to be missing
impls=(
  prezto
  rustup
  apt               # Linux only
  brew
  nix-home-manager  # Requires Nix
  cargo-crates      # Bootstrapped by rustup. May depend on APT/Homebrew/Nix libraries.
  mas               # Bootstrapped by brew
  mise              # Bootstrapped by brew/home-manager or cargo
  uv-tool           # Bootstrapped by brew/home-manager or cargo
  foo
)

hl
echo "Checking functions for each of ${impls[*]}..."
for impl in "${impls[@]}"; do
  # shellcheck disable=SC1090
  source "${impl_dir}/impl-${impl}.sh" || fail "Impl not found for $impl"
  assert_function noun_for_"${impl}"
  assert_function asserts_for_"${impl}"
  assert_function install_or_update_"${impl}"
  assert_function doctor_"${impl}"
done

hl
echo "Updating or installing software 🚀..."
for impl in "${impls[@]}"; do
  # shellcheck disable=SC1090
  hl
  asserts_for_"${impl}" || fail "Failed pre-install checks for ${impl} 😢🎻"
  echo "Updating/installing $(noun_for_"${impl}")..."
  install_or_update_"${impl}"
  echo -n
  echo -n >&2
done

hl
echo "The doctor will see you now 🩺..."
for impl in "${impls[@]}"; do
  # shellcheck disable=SC1090
  hl
  noun="$(noun_for_"${impl}")"
  echo "Checking state of ${noun}..."
  doctor_"${impl}"
  echo -n
  echo -n >&2
done

