#!/bin/bash

fail () {
  echo "$*" >&2
  exit 1
}

[[ -d ".jj" && -d ".git" ]] || fail "Not in a git-based jj repo"

if [[ -n "$(jj git remote list)" ]]; then
  # Note: need to combine stderr and stdout to filter out "Nothing changed." stderr message
  jj git "$@" fetch --all-remotes 2>&1 | awk '!/Nothing changed./'
  [[ "${PIPESTATUS[0]}" -eq 0 ]] || fail "jj git fetch failed"
fi
