#!/bin/bash

# Installs core software, taking into account desired state

function fail() {
  echo "$1" >&2
  exit 1
}

if ! command -v rustup >/dev/null; then
    echo "Installing rustup..."
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
    | bash -s -- -y --no-modify-path \
    || fail "Failed to install rustup"
fi

if ! rustup toolchain list | grep nightly >/dev/null; then
    echo "Adding rust nightly toolchain..."
    rustup toolchain install nightly \
    || fail "Failed to install rust nightly toolchain"
fi

echo "Updating rustup and Rust toolchains..."
rustup update || fail "Failed to update rustup"

echo "Installing (or updating) desired cargo binaries..."
desired_cargo_binaries=$(cat ~/.config/mh/desired-state/cargo-binaries)
for binary in "${desired_cargo_binaries[@]}"; do
  cargo install "$binary" \
  || fail "Failed to install or update cargo binary: $binary"
done
